const supabase = await window.HiddenRoomSupabase.getClient();
const statusElement = document.getElementById('review-status');
const listElement = document.getElementById('review-list');
const producerListElement = document.getElementById('producer-list');
const CLOUD_ORIGIN = 'https://cloud.hiddenroom.mx';
const state = { session: null };
init().catch((error) => { statusElement.textContent = error.message || 'No se pudo cargar la revisión.'; statusElement.classList.add('is-error'); });

async function init() {
  const { data: sessionData } = await supabase.auth.getSession(); state.session = sessionData.session; if (!state.session) { sessionStorage.setItem('hr_return_after_login', location.href); window.location.replace('../../portal/'); return; }
  const { data: profile } = await supabase.from('users').select('roles').eq('user_id', sessionData.session.user.id).maybeSingle(); if (!String(profile?.roles || '').toLowerCase().includes('admin')) throw new Error('Sólo admin puede revisar beats.');
  const [{ data, error }, { data: producers, error: producerError }] = await Promise.all([
    supabase.from('store_products').select('id, slug, name, description, producer, producer_user_id, price, currency, beat_genre, beat_bpm, beat_key, beat_preview_path, beat_preview_status, beat_original_path, beat_cover_path, publication_status, review_comment, submitted_at, producer_profiles(display_name, slug)').eq('category', 'beats').eq('publication_status', 'pending_review').order('submitted_at', { ascending: true }),
    supabase.from('producer_profiles').select('id, display_name, slug, user_id, approval_status, is_active, created_at').eq('approval_status', 'pending').order('created_at', { ascending: true }),
  ]);
  if (error || producerError) throw new Error((error || producerError).message); statusElement.textContent = `${(data || []).length} beat${(data || []).length === 1 ? '' : 's'} esperando revisión.`;
  producerListElement.innerHTML = producers?.length ? producers.map(producerCard).join('') : '<div class="producer-ready-panel"><p>No hay productores pendientes.</p></div>';
  producerListElement.addEventListener('click', handleProducerApproval);
  if (!data?.length) return renderEmpty();
  listElement.innerHTML = data.map(reviewCard).join(''); listElement.addEventListener('click', handleReview);
}

function producerCard(profile) { return `<article class="producer-ready-card" data-producer-id="${escapeHtml(profile.id)}"><span class="producer-ready-badge">Pendiente</span><h3>${escapeHtml(profile.display_name)}</h3><p>@${escapeHtml(profile.slug)} · alta ${escapeHtml(new Intl.DateTimeFormat('es-MX', { dateStyle: 'medium' }).format(new Date(profile.created_at)))}</p><div class="producer-ready-actions"><button class="primary-button" type="button" data-approve-producer="${escapeHtml(profile.id)}">Aprobar productor</button><button class="secondary-button" type="button" data-reject-producer="${escapeHtml(profile.id)}">Rechazar</button></div></article>`; }
async function handleProducerApproval(event) { const button = event.target.closest('[data-approve-producer], [data-reject-producer]'); if (!button) return; button.disabled = true; const approved = button.hasAttribute('data-approve-producer'); const id = button.dataset.approveProducer || button.dataset.rejectProducer; const { error } = await supabase.from('producer_profiles').update({ approval_status: approved ? 'approved' : 'rejected', is_active: approved, approved_at: approved ? new Date().toISOString() : null, approved_by: approved ? state.session.user.id : null }).eq('id', id); if (error) { statusElement.textContent = error.message; statusElement.classList.add('is-error'); button.disabled = false; return; } button.closest('[data-producer-id]')?.remove(); statusElement.textContent = approved ? 'Productor aprobado.' : 'Productor rechazado.'; }

function reviewCard(product) { const preview = product.beat_preview_path ? `${CLOUD_ORIGIN}/api/beat-store/stream?file=${encodeURIComponent(product.beat_preview_path)}` : ''; return `<article class="producer-ready-card producer-ready-review" data-id="${escapeHtml(product.id)}"><div class="producer-ready-card__meta"><span class="producer-ready-badge">En revisión</span><span>${escapeHtml(product.producer_profiles?.display_name || product.producer || 'Productor')}</span></div><h2>${escapeHtml(product.name)}</h2><p>${escapeHtml(product.description || 'Sin descripción.')}</p><p><strong>${escapeHtml(product.beat_genre || 'Género pendiente')}</strong> · ${escapeHtml(product.beat_bpm || 'BPM pendiente')} BPM · ${escapeHtml(product.beat_key || 'Tonalidad pendiente')}</p>${preview ? `<audio class="producer-ready-review__preview" controls preload="none" src="${escapeHtml(preview)}"></audio>` : '<p class="producer-ready-error">Preview no disponible: devolver a productor.</p>'}<p><small>Master registrado: ${product.beat_original_path ? 'sí, protegido' : 'no'} · Portada: ${product.beat_cover_path ? 'sí' : 'no'} · Preview: ${escapeHtml(product.beat_preview_status || 'pendiente')}</small></p><label>Comentario de revisión<textarea data-comment rows="3" placeholder="Motivo si devuelves o inactivas"></textarea></label><div class="producer-ready-actions"><button class="primary-button" type="button" data-decision="approve">Aprobar y publicar</button><button class="secondary-button" type="button" data-decision="return">Devolver</button><button class="secondary-button" type="button" data-decision="inactivate">Inactivar</button></div></article>`; }
async function handleReview(event) { const button = event.target.closest('[data-decision]'); if (!button) return; const card = button.closest('[data-id]'); button.disabled = true; const comment = card.querySelector('[data-comment]').value.trim() || null; const { error } = await supabase.rpc('review_beat_product', { p_beat_id:card.dataset.id, p_decision:button.dataset.decision, p_comment:comment }); if (error) { statusElement.textContent = error.message; statusElement.classList.add('is-error'); button.disabled = false; return; } card.remove(); statusElement.textContent = 'Revisión guardada. El catálogo se actualizará según el estado.'; }
function renderEmpty() { listElement.innerHTML = '<div class="producer-ready-panel"><h2>Bandeja vacía</h2><p>No hay beats pendientes. Los beats devueltos permanecen como borradores del productor.</p></div>'; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char])); }
